/* Offline Warrior presentation. Physics, targeting and network state remain spheres. */
window.CRHumanoids=function(T){
 const template=new T.ObjectLoader().parse(window.CRWarriorData),actors=new Set();
 const idleClip=template.animations.find(c=>c.name==='idle');
 const clips=template.animations.map(c=>{const copy=c.clone();if(c.name==='mv_tar21'){copy.tracks=copy.tracks.map(tr=>{if(!/^Bip001\.|Spine|Neck|Head|UpperArm|Forearm|Hand|Finger|Clavicle/.test(tr.name))return tr;const base=idleClip.tracks.find(t=>t.name===tr.name);if(!base)return tr;const calm=base.clone();for(let i=0;i<calm.times.length;i++)calm.times[i]*=copy.duration/idleClip.duration;return calm;});}for(const tr of copy.tracks){if(tr.name==='Bip001.position'){for(let i=0;i<tr.values.length;i+=3){tr.values[i]=tr.values[0];tr.values[i+2]=tr.values[2];}}}return copy;});
 const kayBank=new Map((window.CRKayKitClips||[]).map(c=>[c.name,T.AnimationClip.parse(c)])),kayActions=window.CRKayKitActions||{};delete window.CRKayKitClips;
 window.CRKayKitRegister=clip=>{if(window.CRKayKitCatalog.includes(clip.name))kayBank.set(clip.name,T.AnimationClip.parse(clip));};
 const loads=new Map();function loadClip(name){if(kayBank.has(name))return Promise.resolve(kayBank.get(name));if(!window.CRKayKitCatalog.includes(name))return Promise.reject(Error('Clip desconocido'));if(loads.has(name))return loads.get(name);const promise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='../assets/kaykit/converted/'+name+'.js';script.onload=()=>{script.remove();kayBank.has(name)?resolve(kayBank.get(name)):reject(Error('Clip inválido'));};script.onerror=()=>{script.remove();loads.delete(name);reject(Error('No se pudo cargar el clip local'));};document.head.append(script);});loads.set(name,promise);return promise;}
 const p=new T.Vector3(),foot=new T.Vector3();let poseCalls=0,skippedPoses=0,poseMs=0;
 const soleCache=new WeakMap();
 function soleVertices(skin){if(soleCache.has(skin.geometry))return soleCache.get(skin.geometry);const g=skin.geometry,ids=g.attributes.skinIndex,weights=g.attributes.skinWeight,pos=g.attributes.position,footBones=new Set(),unique=new Map();skin.skeleton.bones.forEach((b,i)=>{if(/Foot|Toe/.test(b.name))footBones.add(i);});for(const v of new Set(g.index.array)){let w=0;for(let k=0;k<4;k++)if(footBones.has(ids.array[v*4+k]))w+=weights.array[v*4+k];if(w>.5){const key=[pos.getX(v),pos.getY(v),pos.getZ(v)].map(x=>x.toFixed(5)).join(",");if(!unique.has(key))unique.set(key,v);}}const result=[...unique.values()];if(!result.length)throw Error("Warrior: no sole vertices");soleCache.set(g,result);return result;}
 function cloneRig(source){
  const clone=source.clone(true),original=[],copied=[],map=new Map();source.traverse(o=>original.push(o));clone.traverse(o=>copied.push(o));original.forEach((o,i)=>map.set(o,copied[i]));
  original.forEach(o=>{if(!o.isSkinnedMesh)return;const m=map.get(o);m.skeleton=new T.Skeleton(o.skeleton.bones.map(b=>map.get(b)),o.skeleton.boneInverses);m.bindMatrix.copy(o.bindMatrix);m.bindMatrixInverse.copy(o.bindMatrixInverse);if(!m.geometry.boundingSphere)m.geometry.computeBoundingSphere();m.boundingSphere=m.geometry.boundingSphere.clone();m.boundingSphere.radius*=1.8;m.frustumCulled=true;m.geometry.userData.humanoidShared=true;});
  return clone;
 }
 function attach(root,radius,core,face,{player=false,health=null}={}){
  if(root.userData.humanoid)return root.userData.humanoid;
  root.userData.core=core;
  const model=cloneRig(template),factor=radius/18*120,anchor=new T.Group(),accents=new T.Group();
  model.name='warrior-body-rig';model.scale.setScalar(factor);model.position.y=-radius;root.add(model,anchor);anchor.name='original-sphere-head';
  // Reparent the actual original objects: no replacement texture or face material.
  core.scale.setScalar(.42);face.scale.setScalar(.42);anchor.add(core,face,accents);accents.scale.setScalar(.42);
  const source=player?root.userData.rolling:root;
  for(const item of [...source.children])if(item!==model&&item!==anchor&&item!==health&&item!==root.userData.rolling&&!item.isLight)accents.add(item);
  if(player)root.userData.rolling.visible=false;
  const bones=[];let skin;model.traverse(o=>{if(o.isBone)bones.push(o);if(o.isSkinnedMesh){skin=o;const m=core.material.clone();m.emissiveIntensity=.08;o.material=m;o.castShadow=o.receiveShadow=true;}});
  const head=bones.find(b=>/Head/.test(b.name)),feet=bones.filter(b=>/Toe0$/.test(b.name));
  const mixer=new T.AnimationMixer(model),actions={};if(kayBank.size){for(const [key,name] of Object.entries(kayActions)){const clip=kayBank.get('KK_'+name);if(clip){const action=mixer.clipAction(clip);if(['land','reloadOne','reloadTwo','death','pickup','throw','use'].includes(key)){action.setLoop(T.LoopOnce,1);action.clampWhenFinished=true;}actions[key]=action;}}}else{for(const name of ['idle','mv_tar21','atk01','hurt']){const c=clips.find(a=>a.name===name);if(c)actions[name]=mixer.clipAction(c);}}
  actions.idle.play();const data={root,model,anchor,accents,core,face,health,head,feet,skin,mixer,actions,factor,radius,previous:root.position.clone(),speed:0,mode:'idle',elapsed:0,lodTime:0,sole:soleVertices(skin),soleY:0,materials:[],alpha:-1,resetPose:true,grounded:null,airTime:0,airborne:false,locomotion:"idle",landTime:0,preview:null,bodyVertices:skin.geometry.userData.allVertices||(skin.geometry.userData.allVertices=[...new Set(skin.geometry.index.array)])};
  for(const group of [model,anchor])group.traverse(o=>{if(o.isMesh)for(const mat of Array.isArray(o.material)?o.material:[o.material])data.materials.push({mat,opacity:mat.opacity,transparent:mat.transparent,depthWrite:mat.depthWrite});});root.userData.humanoid=data;actors.add(data);pose(data,0,{speed:0,yaw:0,grounded:true});return data;
 }
 function pose(a,dt,{speed=0,yaw=0,grounded=true,verticalSpeed=0,attack=false,hurt=false,dead=false,dash=false,reload=false,interact=false,aim=false,weapon=0,enemy=false}={}){
  const started=performance.now();poseCalls++;dt=T.MathUtils.clamp(Number.isFinite(dt)?dt:0,0,.2);a.elapsed+=dt;a.speed+=(speed-a.speed)*(1-Math.exp(-dt*16));
  // A transient support miss is not a jump. Real upward jumps remain immediate.
  if(grounded){a.airTime=0;a.airborne=false;}else{a.airTime+=dt;a.airborne=a.airborne||verticalSpeed>40||a.airTime>=.08;}
  const supported=!a.airborne;if(a.grounded===false&&supported)a.landTime=.18;a.grounded=supported;a.landTime=Math.max(0,a.landTime-dt);
  // Hysteresis avoids walk/run thrashing when collisions or terrain vary speed.
  if(a.locomotion==='run'){if(a.speed<155)a.locomotion=a.speed>3?'walk':'idle';}
  else if(a.speed>185)a.locomotion='run';else if(a.locomotion==='walk'){if(a.speed<3)a.locomotion='idle';}else if(a.speed>8)a.locomotion='walk';
  const name=a.preview|| (kayBank.size?(dead?'death':hurt?'hurt':dash?'dash':!supported?'jump':reload?(weapon===0?'reloadOne':'reloadTwo'):interact?'interact':attack?(enemy&&a.root.userData.role!==1?'melee':weapon===0?'shotOne':'shotTwo'):a.landTime>0?'land':a.locomotion==='run'?'run':a.locomotion==='walk'?'walk':aim?(weapon===0?'aimOne':'aimTwo'):'idle'):(hurt?'hurt':attack?'atk01':grounded&&a.speed>5?'mv_tar21':'idle'));
  if(a.mode!==name&&a.actions[name]){const previous=a.actions[a.mode],next=a.actions[name],walking=['walk','run'].includes(a.mode)&&['walk','run'].includes(name),phase=walking&&previous?previous.time/previous.getClip().duration:0;previous?.fadeOut(.12);next.reset();if(walking)next.time=(phase%1)*next.getClip().duration;next.fadeIn(.12).play();a.mode=name;}
  const action=a.actions[a.mode];if(action)action.timeScale=['mv_tar21','walk','run'].includes(a.mode)?T.MathUtils.clamp(a.speed/(a.mode==='run'?225:105),.4,2):a.mode==='dash'?2:1;
  a.mixer.update(dt);for(const [key,old] of Object.entries(a.actions))if(key!==a.mode&&old.isRunning()&&old.getEffectiveWeight()===0)old.stop();a.model.rotation.set(0,yaw+Math.PI,0);a.model.position.y=-a.radius;a.root.updateWorldMatrix(true,false);a.model.updateMatrixWorld(true);
  // Contact is visual only; sole alignment uses toe bones, never modifies actor position.
  let min=Infinity;for(const v of (a.preview||a.mode==='death'||/Death|Lie|Crawl|Sit/.test(a.mode)?a.bodyVertices:a.sole)){a.skin.getVertexPosition(v,foot);foot.applyMatrix4(a.skin.matrixWorld);a.root.worldToLocal(foot);min=Math.min(min,foot.y);}
  if(Number.isFinite(min))a.model.position.y+=-a.radius+.35-min;a.model.updateMatrixWorld(true);a.soleY=-a.radius+.35;
  a.head.getWorldPosition(p);a.root.worldToLocal(p);a.anchor.position.copy(p);a.anchor.position.y+=a.factor*.055;
  if(a.health)a.health.position.y=a.anchor.position.y+a.radius*.42+12;
  a.skin.material.color.copy(a.core.material.color);a.skin.material.emissive.copy(a.core.material.emissive);a.skin.material.emissiveIntensity=Math.min(.16,a.core.material.emissiveIntensity*.3);
  // Existing actor visibility owns elimination; never leave a head without its body.
  a.previous.copy(a.root.position);poseMs+=performance.now()-started;
 }
 async function preview(root,name){const a=root.userData.humanoid;if(!a)return;const request=(a.previewRequest||0)+1;a.previewRequest=request;const clip=await loadClip(name);if(request!==a.previewRequest)return;if(!a.actions[name])a.actions[name]=a.mixer.clipAction(clip);a.preview=name;}
 function stopPreview(root){const a=root.userData.humanoid;if(a){a.previewRequest=(a.previewRequest||0)+1;a.preview=null;}}
 function previewActive(root){return !!root.userData.humanoid?.preview;}
 function probe(root,fraction){const a=root.userData.humanoid,name=a.preview||a.mode,action=a.actions[name];a.mixer.stopAllAction();action.reset().stopFading().setEffectiveWeight(1).play();action.time=action.getClip().duration*fraction;a.mode=name;pose(a,0,{});return geometryAudit();}
 function update(root,dt,state){const a=root.userData.humanoid;if(a)pose(a,dt,state);}
 function updateEnemy(root,dt,viewer){const a=root.userData.humanoid;if(!a||!root.visible)return;const range=viewer?root.position.distanceTo(viewer):0,interval=range<500?0:range<1300?1/15:1/6;a.lodTime+=dt;if(dt>0&&a.lodTime<interval&&!root.userData.flash&&!root.userData.windup){skippedPoses++;return;}const step=a.lodTime;a.lodTime=0;const distance=Math.hypot(root.position.x-a.previous.x,root.position.z-a.previous.z);pose(a,step,{speed:step>0&&distance<80?distance/step:0,yaw:0,attack:root.userData.windup>0,hurt:root.userData.flash>0,enemy:true,weapon:root.userData.role===1?1:0});}
 function cameraFade(root,camera,transit=false){const a=root.userData.humanoid;if(!a)return;const alpha=transit?1:T.MathUtils.smoothstep(camera.position.distanceTo(root.position),30,80);if(alpha===a.alpha||(alpha>0&&alpha<1&&Math.abs(alpha-a.alpha)<.005))return;a.alpha=alpha;for(const {mat,opacity,transparent,depthWrite} of a.materials){mat.opacity=opacity*alpha;mat.transparent=transparent||alpha<.999;mat.depthWrite=depthWrite&&alpha>=.999;}}
 function release(root){const a=root.userData.humanoid;if(!a)return;actors.delete(a);a.mixer.stopAllAction();a.mixer.uncacheRoot(a.model);a.skin.material.dispose();a.skin.skeleton.dispose();delete root.userData.humanoid;}
 function cloneTransit(root){const a=root.userData.humanoid,model=cloneRig(a.model),head=a.anchor.clone(true),body=new T.Group(),pairs=[];body.add(model,head);for(const [source,copy] of [[a.model,model],[a.anchor,head]]){const originals=[],copies=[];source.traverse(o=>originals.push(o));copy.traverse(o=>copies.push(o));originals.forEach((o,i)=>pairs.push([o,copies[i]]));}body.userData.syncHumanoidPose=()=>{for(const [source,copy] of pairs){copy.position.copy(source.position);copy.quaternion.copy(source.quaternion);copy.scale.copy(source.scale);}body.updateMatrixWorld(true);};return body;}
 function audit(){return {asset:'Warrior.fbx',actors:actors.size,clips:clips.map(c=>c.name),kaykit:{loaded:kayBank.size,catalog:window.CRKayKitCatalog?.length||0,active:kayBank.size>0},sharedGeometry:true,facesRedrawn:false,collidersChanged:false,performance:{poseCalls,skippedPoses,meanPoseMs:poseCalls?poseMs/poseCalls:0},rigs:[...actors].map(a=>({name:a.root.name,bones:a.skin.skeleton.bones.length,head:a.anchor.position.toArray(),radius:a.radius,headRadius:a.radius*.42,mode:a.mode,clip:a.actions[a.mode]?.getClip().name,rotation:a.model.rotation.toArray().slice(0,3),soleVertices:a.sole.length,soleY:a.soleY,finite:a.skin.skeleton.bones.every(b=>b.matrixWorld.elements.every(Number.isFinite))}))};}
 function geometryAudit(){const result=[];for(const a of actors){if(!a.root.visible)continue;a.root.updateWorldMatrix(true,true);let min=Infinity,max=-Infinity,sole=Infinity,invalid=0;for(const v of new Set(a.skin.geometry.index.array)){a.skin.getVertexPosition(v,p);p.applyMatrix4(a.skin.matrixWorld);a.root.worldToLocal(p);if(!Number.isFinite(p.y))invalid++;min=Math.min(min,p.y);max=Math.max(max,p.y);}for(const v of a.sole){a.skin.getVertexPosition(v,p);p.applyMatrix4(a.skin.matrixWorld);a.root.worldToLocal(p);sole=Math.min(sole,p.y);}result.push({mode:a.mode,minY:min,maxY:max,soleClearance:sole+a.radius,bodyClearance:min+a.radius,tilt:Math.max(Math.abs(a.model.rotation.x),Math.abs(a.model.rotation.z)),invalid});}return result;}
 window.CRHumanoidsTransit=cloneTransit;return {attach,update,updateEnemy,cameraFade,release,cloneTransit,audit,geometryAudit,preview,stopPreview,previewActive,probe};
};
