/* Offline animation preview. Never moves actors or runs simulation. */
window.CRKAnimationLab=function({humanoids,player,allowed,pause,paused,overlay}){
 const panel=document.createElement('section');panel.hidden=true;panel.style.cssText='position:fixed;right:20px;top:100px;width:290px;padding:16px;background:#071310ed;border:1px solid #778575;border-radius:12px;color:#d9dfce;z-index:100;font:13px Segoe UI';
 const title=document.createElement('b');title.textContent='KAYKIT · LABORATORIO';const note=document.createElement('p');note.textContent='130 animaciones · física pausada · sólo presentación';const select=document.createElement('select');select.style.cssText='width:100%;padding:8px;background:#18221f;color:#e0e6d6';for(const name of window.CRKayKitCatalog){const o=document.createElement('option');o.value=name;o.textContent=name.replace(/^KK_/,'').replaceAll('_',' ');select.append(o);}select.value='KK_Idle_A';
 const play=document.createElement('button'),close=document.createElement('button'),status=document.createElement('p');play.textContent='▶ Probar';close.textContent='Volver al juego · F7';for(const b of [play,close])b.style.cssText='margin-top:10px;padding:8px;background:#23362e;color:#e0e6d6;border:1px solid #718173;border-radius:5px;width:100%';panel.append(title,note,select,play,close,status);document.body.append(panel);let wasPaused=false,wasHidden=true,request=0;
 async function run(){const seq=++request;status.textContent='Cargando archivo local…';play.disabled=true;try{await humanoids.preview(player,select.value);if(seq===request)status.textContent=select.selectedOptions[0].textContent;}catch(e){status.textContent=e.message;}finally{if(seq===request)play.disabled=false;}}
 function shut(){request++;humanoids.stopPreview(player);panel.hidden=true;pause(wasPaused);overlay.hidden=wasHidden;play.disabled=false;}
 function toggle(){if(!panel.hidden){shut();return;}if(!allowed())return;wasPaused=paused();wasHidden=overlay.hidden;pause(true);overlay.hidden=true;panel.hidden=false;document.exitPointerLock?.();run();}
 play.onclick=run;select.onchange=run;close.onclick=shut;addEventListener('keydown',e=>{if(e.code==='F7'&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();toggle();}else if(!panel.hidden){e.stopImmediatePropagation();if(e.code==='Escape'){e.preventDefault();shut();}}});
};
