/* Local identities are separate from temporary match actor IDs and equipment. */
(function(root){'use strict';
 const KEY='CR3D-profiles-v2',names=[['Carlitos','Martín','Pepe','Cristian','Ana','Luz'],['Julián','Eduardo','Pablo','Nahuel','Sol','Leo']];let counter=0;
 const clip=(value,n)=>{const s=String(value??'').trim();return typeof Intl.Segmenter==='function'?Array.from(new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(s),a=>a.segment).slice(0,n).join(''):Array.from(s).slice(0,n).join('');};
 const id=()=>root.crypto?.randomUUID?.()||'local-'+Date.now().toString(36)+'-'+(++counter);
 function normalize(input=[]){return Array.from({length:4},(_,i)=>{const raw=input[i]||{},old=String(raw.name||''),defaultName='Equipo de prueba '+(i+1);return {profileId:clip(raw.profileId||id(),64),name:clip(!old||/^Equipo (\d+|Ámbar|Jade)$/.test(old)?defaultName:old,30)||defaultName,members:Array.from({length:6},(_,j)=>{const v=raw.members?.[j],p=v&&typeof v==='object'?v:{name:v};return {profileId:clip(p.profileId||id(),64),name:clip(p.name,24)||names[i]?.[j]||'Jugador '+(i+1)+'-'+(j+1),avatar:clip(p.avatar,2),cosmetics:{skinId:'default'}};})};});}
 function read(storage){try{const saved=JSON.parse(storage.getItem(KEY)||'null');if(saved?.schema===2&&Array.isArray(saved.teams))return normalize(saved.teams);const legacy=JSON.parse(storage.getItem('CR3D-roster-v1')||'[]');return normalize(Array.isArray(legacy)?legacy:[]);}catch(_){return normalize();}}
 function createEditor({overlay,count,size,storage}){
   const teams=read(storage),details=document.createElement('details');details.className='roster-editor';details.id='team-editor';const summary=document.createElement('summary');summary.textContent='Crear equipos · nombres de jugadores y emojis';const note=document.createElement('p');note.textContent='Cada jugador conserva su identidad en esta PC. El símbolo aparece en la partida; las skins llegarán más adelante.';note.className='profile-note';const area=document.createElement('div');area.className='roster-fields';details.append(summary,note,area);overlay.append(details);
   function save(){try{storage.setItem(KEY,JSON.stringify({schema:2,teams}));}catch(_){}}save();
   function build(){area.replaceChildren();for(let i=0;i<Number(count.value);i++){const section=document.createElement('section'),label=document.createElement('label');label.textContent='Equipo '+(i+1);section.append(label);const teamInput=document.createElement('input');teamInput.dataset.team=i;teamInput.dataset.member=-1;teamInput.maxLength=256;teamInput.setAttribute('aria-label','Nombre de equipo '+(i+1));teamInput.value=teams[i].name;teamInput.oninput=()=>{teams[i].name=clip(teamInput.value,30);save();};section.append(teamInput);
     for(let j=0;j<Number(size.value);j++){const row=document.createElement('div');row.className='profile-row';const name=document.createElement('input'),avatar=document.createElement('input');name.dataset.team=i;name.dataset.member=j;name.maxLength=256;name.value=teams[i].members[j].name;name.setAttribute('aria-label','Nombre del jugador '+(j+1)+' de equipo '+(i+1));avatar.dataset.avatar='true';avatar.dataset.team=i;avatar.dataset.player=j;avatar.className='profile-avatar';avatar.maxLength=64;avatar.placeholder='👾';avatar.value=teams[i].members[j].avatar;avatar.setAttribute('aria-label','Símbolo o emoji del jugador '+(j+1)+' de equipo '+(i+1));name.oninput=()=>{teams[i].members[j].name=clip(name.value,24);save();};avatar.oninput=()=>{teams[i].members[j].avatar=clip(avatar.value,2);save();};row.append(name,avatar);section.append(row);}area.append(section);}}
   build();count.addEventListener('change',build);size.addEventListener('change',build);
   return {teams(n=Number(count.value),m=Number(size.value)){return teams.slice(0,n).map((t,i)=>({profileId:t.profileId,name:t.name||'Equipo de prueba '+(i+1),members:t.members.slice(0,m).map((p,j)=>({...p,name:p.name||'Jugador '+(j+1),cosmetics:{...p.cosmetics}}))}));},lock(value){for(const input of area.querySelectorAll('input'))input.disabled=value;count.disabled=size.disabled=value;}};
 }
 const api={clip,normalize,read,createEditor};if(typeof module==='object')module.exports=api;else root.CRProfiles=api;
})(typeof window==='object'?window:globalThis);
