/* Fixed geometry pools; presentation/telemetry updates at render cadence. */
window.CRStrategyView=function({T,scene,heightAt,icons,catalog,select,use}){
 const root=new T.Group();root.name='tactical-world';scene.add(root);
 const goalPool=[],effectPool=[],palette={relay:'#a9d7bb',zone:'#d7b97f',cargo:'#af92db',extract:'#8dcfd0',pve:'#db837f',resonator:'#b6a7cf',breach:'#d4bc87',smoke:'#8b8b9c',sensor:'#83d4ce',acid:'#96ae69',messenger:'#bd9dce'};
 const ringGeo=new T.TorusGeometry(1,.016,5,48),bodyGeo=new T.OctahedronGeometry(1,0),cloudGeo=new T.IcosahedronGeometry(1,1);
 function slot(){const g=new T.Group(),material=new T.MeshBasicMaterial({color:'#a9d7bb',transparent:true,opacity:.65,depthWrite:false}),ring=new T.Mesh(ringGeo,material),body=new T.Mesh(bodyGeo,material),cloud=new T.Mesh(cloudGeo,new T.MeshBasicMaterial({color:'#9299ad',transparent:true,opacity:.18,depthWrite:false,wireframe:true}));ring.rotation.x=Math.PI/2;body.position.y=26;body.scale.setScalar(9);cloud.scale.set(60,40,60);g.add(ring,body,cloud);g.visible=false;root.add(g);return {g,ring,body,cloud,material};}
 for(let i=0;i<12;i++)goalPool.push(slot());for(let i=0;i<40;i++)effectPool.push(slot());
 const preview=slot();preview.body.visible=false;preview.cloud.visible=false;preview.material.opacity=.85;
 const hud=document.createElement('section');hud.id='strategy-hud';hud.setAttribute('aria-label','Objetivos y herramientas');const objectives=document.createElement('div'),visibility=document.createElement('div'),contract=document.createElement('div'),effects=document.createElement('small'),tools=document.createElement('div'),help=document.createElement('small');tools.className='strategy-tools';help.textContent='G · usar herramienta seleccionada hacia la mira · E · objetivo';
 for(const [kind,def] of Object.entries(catalog)){const b=document.createElement('button');b.dataset.tool=kind;b.title=def.description+' Contrajuego: '+def.counter;b.append(icons.make(def.icon),document.createElement('span'));b.onclick=()=>select(kind);tools.append(b);}
 const fire=document.createElement('button');fire.className='strategy-use';fire.textContent='G · Usar herramienta';fire.onclick=()=>use();hud.append(objectives,visibility,contract,effects,tools,fire,help);document.body.append(hud);let bodies=[],lastTime=-1;
 function paint(slot,data,kind,time){slot.material.opacity=.65;slot.body.rotation.z=0;slot.g.visible=true;slot.g.position.fromArray(data.position);slot.material.color.set(palette[kind]||'#a9d7bb');slot.ring.scale.setScalar(data.radius||18);slot.ring.position.y=-17.5;slot.body.visible=kind!=='smoke';slot.cloud.visible=kind==='smoke';slot.body.rotation.y=time;slot.body.position.y=['messenger','sensor'].includes(kind)?0:26;slot.g.userData={strategyObject:true,id:data.id,radius:kind==='messenger'?18:12,alive:data.hp>0};}
 function update(s,{time=0,actorId=null,teamId=null,position=[0,0,0],yaw=0,selected='smoke',aim=null,valid=false,visibility:vis={seen:false,reason:''},paused=false,controls=true}={}){
   root.visible=s.enabled;hud.hidden=!s.enabled||paused;bodies=[];for(const p of [...goalPool,...effectPool])p.g.visible=false;if(!s.enabled){preview.g.visible=false;return;}
   s.goals.slice(0,12).forEach((g,i)=>{if(g.carrier)return;paint(goalPool[i],g,g.type,time);goalPool[i].body.visible=g.type!=='pve'||g.available;if(['resonator','breach'].includes(g.type)){const ready=g.requires.every(id=>s.goals.find(n=>n.id===id)?.complete.includes(teamId)),done=g.complete.includes(teamId);goalPool[i].material.color.set(done?'#94d5bc':ready?palette[g.type]:'#665e75');goalPool[i].body.scale.setScalar(g.type==='breach'?15:11);goalPool[i].body.rotation.z=Math.sin(time*1.3)*.15;goalPool[i].material.opacity=done?.35:ready?.85:.4;}else goalPool[i].body.scale.setScalar(9);});
   [...s.fields,...s.couriers.map(c=>({...c,kind:'messenger',radius:18}))].slice(0,40).forEach((f,i)=>{paint(effectPool[i],f,f.kind,time);if(f.hp>0)bodies.push(effectPool[i].g);});
   preview.g.visible=!!aim&&!paused&&catalog[selected].range>0;if(aim){const dt=lastTime<0?1:Math.max(0,time-lastTime);preview.g.position.lerp(new T.Vector3(...aim),1-Math.exp(-dt*32));lastTime=time;preview.ring.scale.setScalar(catalog[selected].radius||18);preview.material.color.set(valid?'#acd9bd':'#cc746f');}
   const mine=s.stocks.find(o=>o.id===actorId)?.items||{},c=s.contracts.find(c=>c.id===actorId),d=g=>Math.hypot(g.position[0]-position[0],g.position[2]-position[2]);const goalText=[...s.goals].sort((a,b)=>d(a)-d(b)).slice(0,3).map(g=>{const a=Math.atan2(-(g.position[0]-position[0]),-(g.position[2]-position[2]))-yaw,arrow=Math.abs(Math.atan2(Math.sin(a),Math.cos(a)))<.7?'↑':Math.sin(a)>0?'→':'←';return arrow+' '+g.name+' · '+Math.round(d(g)/10)+' m'+(g.type==='relay'?' '+Math.min(g.required,g.progress)+'/'+g.required:g.type==='zone'?' +2/turno':['resonator','breach'].includes(g.type)?(g.complete.includes(teamId)?' ✓':g.requires.some(id=>!s.goals.find(n=>n.id===id)?.complete.includes(teamId))?' 🔒':(s.channel?.goalId===g.id?' ◉ ':' ◇ ')+Math.floor((g.work[teamId]||0)/g.workSeconds*100)+'%'):g.carrier?' en tránsito':g.type==='pve'&&!g.available?' despejar':' E');}).join(' | ');
   const circuit=s.goals.filter(g=>g.type==='resonator'),breach=s.goals.find(g=>g.type==='breach');const circuitText=circuit.length?'◇ CIRCUITO '+circuit.filter(g=>g.complete.includes(teamId)).length+'/'+circuit.length+' · '+(breach?.complete.includes(teamId)?'BRECHA COMPLETADA':breach?.requires.every(id=>s.goals.find(n=>n.id===id)?.complete.includes(teamId))?'BRECHA HABILITADA':'BRECHA SELLADA')+' | ':'';const displayText=circuitText+goalText;if(objectives.textContent!==displayText)objectives.textContent=displayText;visibility.textContent=(vis.seen?'◉ EXPUESTO':'◌ OCULTO')+' · '+vis.reason;visibility.dataset.seen=String(vis.seen);contract.textContent='◆ Contrato privado: '+(c?c.name+(c.done?' · CUMPLIDO':''):'solo visible para su equipo');const effectText=s.fields.map(f=>catalog[f.kind].name+' '+f.remaining+' turnos').join(' · ');if(effects.textContent!==effectText)effects.textContent=effectText;
   for(const b of tools.children){const k=b.dataset.tool,def=catalog[k];b.querySelector('span').textContent=def.name+' ×'+(mine[k]||0);b.classList.toggle('selected',selected===k);b.disabled=!controls||!mine[k];}fire.textContent='G · '+catalog[selected].name+' ×'+(mine[selected]||0);fire.disabled=!controls||!mine[selected]||!valid;
 }
 function reset(){lastTime=-1;root.visible=false;hud.hidden=true;preview.g.visible=false;bodies=[];}
 reset();return {update,reset,bodies:()=>bodies,stats:()=>({goals:12,effects:40,objects:bodies.length})};
};
