'use strict';const assert=require('node:assert/strict'),S=require('./strategy.js');let checks=0;const ok=(v,n)=>{assert(v,n);checks++;};
const members=[{id:'a',teamId:'red',hp:100},{id:'b',teamId:'red',hp:100},{id:'c',teamId:'blue',hp:100}],p={a:[0,18,0],b:[500,18,0],c:[600,18,0]};let actor=members[0],phase='active',blocked=false,scores={red:0,blue:0};
const defs=[0,1,2].map(i=>({id:'r'+i,type:'resonator',position:[i*150,18,0],radius:40,workSeconds:6,points:2}));defs.push({id:'gate',type:'breach',position:[450,18,0],radius:40,workSeconds:8,points:18,requires:['r0','r1','r2']});
const game=S.create({actors:()=>members,active:()=>actor,phase:()=>phase,position:id=>p[id],los:()=>!blocked,award:(id,n)=>scores[members.find(m=>m.id===id).teamId]+=n});
const start=()=>{actor=members[0];phase='active';blocked=false;scores={red:0,blue:0};members.forEach(m=>m.hp=100);p.a=[0,18,0];p.b=[500,18,0];p.c=[600,18,0];game.start(defs);};start();p.a=[450,18,0];game.interact('a');game.tick(10);ok(scores.red===0&&!game.snapshot().channel,'Locked exit cannot award points');
start();ok(game.interact('a'),'Start timed work');game.tick(2);ok(game.snapshot().goals[0].work.red===2,'Actual elapsed work');game.interact('a');ok(game.snapshot().goals[0].work.red===2,'Repeated E cannot duplicate/reset work');p.a=[10,18,0];game.tick(.1);ok(!game.snapshot().channel&&game.snapshot().goals[0].work.red===2,'Movement interrupts preserving progress');p.a=[0,18,0];game.interact('a');members[0].hp=99;game.tick(.1);ok(!game.snapshot().channel,'Damage interrupts');game.interact('a');blocked=true;game.tick(.1);ok(!game.snapshot().channel,'Occluding wall interrupts');blocked=false;game.interact('a');p.c=[20,18,0];game.tick(.1);ok(!game.snapshot().channel,'Rival presence interrupts');p.c=[600,18,0];game.interact('a');game.onEnd('a');const progress=game.snapshot().goals[0].work.red;phase='settling';game.tick(20);ok(game.snapshot().goals[0].work.red===progress&&!game.snapshot().channel,'No work during turn wait');phase='active';actor=members[1];p.b=[0,18,0];game.interact('b');game.tick(4);ok(game.snapshot().goals[0].complete.includes('red'),'Teammate resumes shared progress');ok(scores.red>=2,'Team completion rewards objectives');const score=scores.red;game.interact('b');game.tick(10);ok(scores.red===score,'Cannot farm completion');actor=members[2];p.c=[0,18,0];p.a=[500,18,0];p.b=[500,18,0];game.interact('c');game.tick(1);ok(game.snapshot().goals[0].work.blue===1,'Rival team has independent progress');
start();for(let i=0;i<3;i++){p.a=[i*150,18,0];game.interact('a');game.tick(6);}p.a=[450,18,0];game.interact('a');game.tick(8);ok(scores.red===24&&members.every(m=>m.hp===100),'Circuit and extraction yield victory score without kills');ok(game.snapshot().goals[3].complete.includes('red'),'Breach completes only after three prerequisites');
start();game.interact('a');game.tick(2);const saved=game.snapshot();saved.goals[0].work.red=99;ok(game.snapshot().goals[0].work.red===2,'Snapshot work cannot mutate authority');const clone=S.create({actors:()=>members,active:()=>actor,phase:()=>phase,position:id=>p[id],los:()=>true,award:()=>{}});clone.restore(game.snapshot());ok(clone.snapshot().channel.goalId==='r0'&&clone.snapshot().goals[0].work.red===2,'Replication carries channel and progress');game.tick(NaN);ok(Number.isFinite(game.snapshot().elapsed),'Invalid dt cannot corrupt state');ok(game.snapshot().reveals.some(r=>r.id==='a'&&r.kind==='resonador'),'Working produces stealth reveal');
assert.throws(()=>game.start([{...defs[3],requires:['missing']}]),/dependencies/);checks++;console.log('CIRCUIT PASS: '+checks+' checks');
