window.CRTurnView=function({T,scene,player,turns,heightAt,collisions,characterStyle,humanoids,readable=()=>true,stealth=()=>false}){
 const ghosts=new Map(),labels=new Map(),root=new T.Group();scene.add(root);const style=characterStyle||window.CRCharacterStyle(T),colors=style.teamColors;
 function build(){clear();for(const m of turns.members){const team=Number(m.teamId.split('-')[1]),body=new T.Group(),mesh=style.body(18,colors[team]);body.add(mesh);body.userData={actorId:m.id,radius:18,alive:true};const index=turns.members.filter(a=>a.teamId===m.teamId).indexOf(m);body.position.set((team%2?1:-1)*(140+Math.floor(team/2)*240),heightAt((team%2?1:-1)*(140+Math.floor(team/2)*240),90+index*60)+18,90+index*60);collisions.resolve(body.position,18);m.data.position=body.position.toArray();m.data.spawn=[...m.data.position];root.add(body);ghosts.set(m.id,body);
  const canvas=document.createElement('canvas');canvas.width=256;canvas.height=96;const texture=new T.CanvasTexture(canvas),sprite=new T.Sprite(new T.SpriteMaterial({map:texture,depthWrite:false}));sprite.scale.set(85,32,1);body.add(sprite);sprite.position.y=35;const face=style.face(18,index);body.add(face);body.userData.face=face;labels.set(m.id,{canvas,texture,sprite,last:''});humanoids?.attach(body,18,mesh,face,{health:sprite});sprite.position.y=58;}
 }
 function sync(){if(!turns.enabled)return;const current=turns.active();if(current){current.hp=Math.max(0,current.hp);current.data.position=player.position.toArray();player.visible=current.hp>0;}for(const m of turns.members){const body=ghosts.get(m.id);if(!body)continue;body.userData.alive=m.hp>0;body.userData.readable=readable(m.id);body.rotation.y=m.data.yaw||0;body.userData.core.material.emissiveIntensity=body.userData.readable?.16:0;labels.get(m.id).sprite.visible=body.userData.readable;body.visible=m.id!==current?.id&&m.hp>0&&!m.hidden&&(!stealth()||body.userData.readable);if(m.data.position)body.position.fromArray(m.data.position);if(body.visible)humanoids?.update(body,0,{yaw:0});const label=labels.get(m.id),text=(m.avatar?m.avatar+' ':'')+m.name+' · '+Math.ceil(m.hp)+' HP'+(m.statuses.length?' · '+m.statuses.map(s=>s.type==='poison'?'VENENO':'ESCUDO').join(','):'');if(label.last!==text){label.last=text;const q=label.canvas.getContext('2d');q.clearRect(0,0,256,96);q.fillStyle='#06110ed9';q.fillRect(0,12,256,70);q.font='bold 18px Segoe UI';q.fillStyle='#e6e9d1';q.textAlign='center';q.fillText((m.avatar?m.avatar+' ':'')+m.name,128,39,240);q.font='15px Segoe UI';q.fillText(Math.ceil(m.hp)+' HP'+(m.statuses.length?' · '+(m.statuses[0].type==='poison'?'VENENO':'ESCUDO'):''),128,66);label.texture.needsUpdate=true;}}
 }
 function bodies(allTeams=true){const active=turns.active();return [...ghosts.values()].filter(b=>b.userData.alive&&b.userData.actorId!==active?.id&&(allTeams||turns.members.find(m=>m.id===b.userData.actorId)?.teamId!==active?.teamId));}
 function nearest(position,eligible=()=>true){let target=eligible(player)?player:null,distance=turns.active()?.hp>0&&eligible(player)?position.distanceToSquared(player.position):Infinity;for(const body of bodies()){if(!eligible(body))continue;const d=position.distanceToSquared(body.position);if(d<distance){target=body;distance=d;}}return target;}
 function clear(){for(const g of ghosts.values())humanoids?.release(g);for(const g of ghosts.values())g.traverse(o=>{if(o.geometry&&!o.geometry.userData.humanoidShared)o.geometry.dispose();if(o.material){if(!o.material.map?.userData.characterShared)o.material.map?.dispose();if(!o.isSkinnedMesh)o.material.dispose();}});root.clear();ghosts.clear();labels.clear();}
 return {build,sync,bodies,nearest,clear};
};
