'use strict';const fs=require('node:fs'),zlib=require('node:zlib'),crypto=require('node:crypto');
const data=fs.readFileSync(process.argv[2]),version=data.readUInt32LE(23);let at=27;
const u32=()=>{const n=data.readUInt32LE(at);at+=4;return n;},u64=()=>{const n=Number(data.readBigUInt64LE(at));at+=8;return n;};
function prop(){const t=String.fromCharCode(data[at++]);if(t==='S'||t==='R'){const n=u32(),b=data.subarray(at,at+n);at+=n;return t==='S'?b.toString('utf8').replaceAll('\u0000\u0001','::'):b.length;}const sizes={Y:2,C:1,I:4,F:4,D:8,L:8};if(sizes[t]){const n=t==='Y'?data.readInt16LE(at):t==='C'?!!data[at]:t==='I'?data.readInt32LE(at):t==='F'?data.readFloatLE(at):t==='D'?data.readDoubleLE(at):Number(data.readBigInt64LE(at));at+=sizes[t];return n;}if('fdlibc'.includes(t)){const count=u32(),encoding=u32(),length=u32();let b=data.subarray(at,at+length);at+=length;if(encoding)b=zlib.inflateSync(b);const values=[],size={f:4,d:8,l:8,i:4,b:1,c:1}[t];for(let i=0;i<count;i++)values.push(t==='f'?b.readFloatLE(i*size):t==='d'?b.readDoubleLE(i*size):t==='l'?Number(b.readBigInt64LE(i*size)):t==='i'?b.readInt32LE(i*size):b[i]);return values;}throw Error('Unknown property '+t);}
function node(){const end=version>=7500?u64():u32(),count=version>=7500?u64():u32();version>=7500?u64():u32();const length=data[at++];if(!end)return null;const name=data.subarray(at,at+length).toString();at+=length;const props=Array.from({length:count},prop),children=[];while(at<end){const c=node();if(!c)break;children.push(c);}at=end;return {name,props,children};}
const roots=[];while(at<data.length){const n=node();if(!n)break;roots.push(n);}const root=n=>roots.find(v=>v.name===n),objects=root('Objects').children,child=(n,k)=>n.children.find(v=>v.name===k),properties=n=>Object.fromEntries((child(n,'Properties70')?.children||[]).filter(p=>p.name==='P').map(p=>[p.props[0],p.props.slice(4)]));
const models=objects.filter(o=>o.name==='Model'),geometries=objects.filter(o=>o.name==='Geometry'),clusters=objects.filter(o=>o.name==='Deformer'&&o.props[2]==='Cluster'),stacks=objects.filter(o=>o.name==='AnimationStack');
const report={source:'https://github.com/mrdoob/three.js/blob/13a06fc663fcf35de89a1044f64b40ef499e6f2e/examples/models/fbx/warrior/Warrior.fbx',fileBytes:data.length,sha256:crypto.createHash('sha256').update(data).digest('hex'),version,global:properties(root('GlobalSettings')),header:root('FBXHeaderExtension')?.children.filter(n=>n.name==='Creator').map(n=>n.props),bones:models.filter(o=>o.props[2]==='LimbNode').map(o=>({id:o.props[0],name:o.props[1],...properties(o)})),meshes:geometries.map(o=>{const v=child(o,'Vertices')?.props[0]||[],idx=child(o,'PolygonVertexIndex')?.props[0]||[];const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<v.length;i++){min[i%3]=Math.min(min[i%3],v[i]);max[i%3]=Math.max(max[i%3],v[i]);}let triangles=0,n=0;for(const i of idx){n++;if(i<0){triangles+=n-2;n=0;}}return {name:o.props[1],vertices:v.length/3,triangles,bounds:{min,max},layers:o.children.filter(n=>n.name.startsWith('Layer')).map(n=>n.name)};}),clusters:clusters.map(o=>({name:o.props[1],influencedVertices:child(o,'Indexes')?.props[0].length})),animations:stacks.map(o=>{const p=properties(o);return {name:o.props[1],startSeconds:p.LocalStart?.[0]/46186158000,stopSeconds:p.LocalStop?.[0]/46186158000,durationSeconds:(p.LocalStop?.[0]-p.LocalStart?.[0])/46186158000};}),textures:objects.filter(o=>o.name==='Texture'||o.name==='Video').map(o=>({type:o.name,name:o.props[1],file:child(o,'FileName')?.props,relative:child(o,'RelativeFilename')?.props})),materialNames:objects.filter(o=>o.name==='Material').map(o=>o.props[1]),models:models.filter(o=>o.props[2]!=='LimbNode').map(o=>({name:o.props[1],type:o.props[2],...properties(o)}))};
const byId=new Map(objects.map(o=>[o.props[0],o])),children=new Map();for(const c of root('Connections').children){const[,source,target]=c.props;if(!children.has(target))children.set(target,[]);children.get(target).push(source);}
for(let i=0;i<stacks.length;i++){const seen=new Set(),times=[];function visit(id){if(seen.has(id))return;seen.add(id);const o=byId.get(id);if(!o||!o.name.startsWith('Animation'))return;const keys=child(o,'KeyTime')?.props[0];if(keys?.length)times.push(keys[0],keys[keys.length-1]);for(const c of children.get(id)||[])visit(c);}visit(stacks[i].props[0]);if(times.length){const start=Math.min(...times)/46186158000,end=Math.max(...times)/46186158000;Object.assign(report.animations[i],{startSeconds:start,stopSeconds:end,durationSeconds:end-start});}}
report.license={status:'unconfirmed-do-not-package',author:'unknown',originalSource:'Unity Asset Store, package not identified',appliesTo:'model, original texture, all eight clips',evidence:'https://github.com/mrdoob/three.js/issues/22167'};
fs.writeFileSync(process.argv[3],JSON.stringify(report,null,2));console.log(JSON.stringify({version,bones:report.bones.length,meshes:report.meshes,animations:report.animations,textures:report.textures,global:report.global},null,2));
