/* Bounded item pool. Supply randomness is independent of combat and decoration. */
window.CRSupplies=function({T,scene,collisions,heightAt,actors,sound}){
const pool=[],colors={tool:'#a9b2d9',ammo:'#c6ae65',medkit:'#bf727a',shield:'#7cb7d2',antidote:'#96b58c'},labels={tool:'HERRAMIENTA',ammo:'MUNICIÓN',medkit:'BOTIQUÍN',shield:'ESCUDO',antidote:'ANTÍDOTO'},root=new T.Group();scene.add(root);let seed=937,id=0,now=0,lastTarget=null;
function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
for(let i=0;i<12;i++){const group=new T.Group(),body=new T.Mesh(new T.BoxGeometry(18,18,18),new T.MeshStandardMaterial({color:'#6a7954',roughness:.83}));group.add(body);const trim=new T.Mesh(new T.BoxGeometry(19,4,19),new T.MeshStandardMaterial({color:'#b9c89b',roughness:.72}));group.add(trim);const canopy=new T.Group(),cloth=new T.Mesh(new T.SphereGeometry(26,12,6,0,Math.PI*2,0,Math.PI/2),new T.MeshStandardMaterial({color:'#babd9e',side:T.DoubleSide,roughness:1}));cloth.position.y=42;canopy.add(cloth);for(const x of [-9,9])for(const z of [-9,9]){const g=new T.BufferGeometry().setFromPoints([new T.Vector3(x,10,z),new T.Vector3(x*2,42,z*2)]);canopy.add(new T.Line(g,new T.LineBasicMaterial({color:'#a3b398'})));}group.add(canopy);const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const texture=new T.CanvasTexture(canvas),badge=new T.Sprite(new T.SpriteMaterial({map:texture,depthWrite:false}));badge.position.y=23;badge.scale.set(55,14,1);group.add(badge);const beacon=new T.Mesh(new T.TorusGeometry(16,.7,5,24),new T.MeshBasicMaterial({color:'#c6ae65',transparent:true,opacity:.5}));beacon.rotation.x=Math.PI/2;beacon.position.y=-8;group.add(beacon);group.visible=false;root.add(group);pool.push({group,body,canopy,badge,beacon,canvas,texture,active:false,landed:false,age:0});}
function paint(s){const color=colors[s.payload.type],q=s.canvas.getContext('2d');q.clearRect(0,0,256,64);q.fillStyle='#0a1611dd';q.fillRect(0,0,256,64);q.font='bold 21px Segoe UI';q.fillStyle=color;q.textAlign='center';q.fillText(labels[s.payload.type],128,40);s.texture.needsUpdate=true;s.body.material.color.set(color);s.beacon.material.color.set(color);}
function spawn(target=null,type=null){if(type==='fuel')return null;const list=actors();const actor=target||list[Math.floor(random()*Math.max(1,list.length))]||{id:'solo',position:[0,heightAt(0,0)+18,0]},p=actor.position||[0,20,0];lastTarget=actor.id;let x,z,landing;for(let attempt=0;attempt<20;attempt++){const a=random()*Math.PI*2,r=95+random()*135;x=T.MathUtils.clamp(p[0]+Math.cos(a)*r,-3400,3400);z=T.MathUtils.clamp(p[2]+Math.sin(a)*r,-3400,3400);const floor=heightAt(x,z),from=new T.Vector3(x,floor+850,z),to=new T.Vector3(x,floor-30,z),hit=collisions.hit(from,to,10);landing=from.clone().lerp(to,hit??1);landing.y=Math.max(landing.y,floor+10);if(landing.y<=Math.max(floor+10,p[1]+10)+65)break;}const s=pool.find(s=>!s.active)||pool.reduce((a,b)=>a.age>b.age?a:b),roll=random();type=type|| (roll<.55?'ammo':roll<.7?'medkit':roll<.82?'shield':'antidote');s.payload=type==='ammo'?{type,amounts:[14,28,6,1]}:{type};s.id=++id;s.active=true;s.landed=false;s.age=0;s.landing=landing;s.startY=landing.y+360;s.group.position.set(x,s.startY,z);s.group.visible=true;s.canopy.visible=true;paint(s);return s.id;}
function update(dt,time,visualOnly=false){now=time;for(const s of pool){if(!s.active)continue;if(!visualOnly){s.age+=dt;if(s.age>240){s.active=false;s.group.visible=false;continue;}const k=Math.min(1,s.age/2.6);s.group.position.y=s.landing.y+(s.startY-s.landing.y)*(1-k)*(1-k);if(k===1&&!s.landed){s.landed=true;s.canopy.visible=false;sound.event('land',s.group.position);}}if(visualOnly&&s.remotePosition)s.group.position.lerp(s.remotePosition,1-Math.exp(-dt*26));s.beacon.rotation.z=time*.5;s.badge.position.y=23+Math.sin(time*1.8+s.id)*1.2;}}
function near(position){return pool.filter(s=>s.active&&s.landed&&s.group.position.distanceTo(position)<46&&collisions.hit(position,s.group.position)===null).sort((a,b)=>a.group.position.distanceToSquared(position)-b.group.position.distanceToSquared(position))[0]||null;}
function collect(position,apply){const s=near(position);if(!s||!apply(s.payload))return null;s.active=false;s.group.visible=false;sound.event('reward',s.group.position);return {...s.payload};}
function snapshot(){return {lastTarget,crates:pool.filter(s=>s.active).map(s=>({id:s.id,payload:s.payload,age:s.age,landed:s.landed,position:s.group.position.toArray(),landing:s.landing.toArray(),startY:s.startY}))};}
function restore(data){lastTarget=data?.lastTarget;for(let i=0;i<pool.length;i++){const s=pool[i],d=data?.crates?.[i];s.active=!!d;s.group.visible=!!d;if(!d)continue;const changed=s.id!==d.id||s.payload?.type!==d.payload.type;Object.assign(s,{id:d.id,payload:d.payload,age:d.age,landed:d.landed,startY:d.startY});s.landing=new T.Vector3(...d.landing);s.remotePosition=new T.Vector3(...d.position);if(changed)s.group.position.copy(s.remotePosition);s.canopy.visible=!d.landed;if(changed)paint(s);}}
function reset(){id=0;seed=window.crypto.getRandomValues(new Uint32Array(1))[0]||937;lastTarget=null;for(const s of pool){s.active=false;s.id=0;s.payload=null;s.remotePosition=null;s.group.visible=false;}}
return {spawn,update,near,collect,snapshot,restore,reset,labels};
};
