'use strict';
// Desktop-to-desktop TCP, bounded newline JSON; no dependencies or browser privileges.
const net=require('node:net'),crypto=require('node:crypto'),os=require('node:os');
const {StringDecoder}=require('node:string_decoder');
const VERSION='0.17.0',PORT=49321,MAX=160000;
function channel(socket,onMessage,onClose){let buffer='',closed=false;const decoder=new StringDecoder('utf8');socket.setNoDelay(true);socket.setKeepAlive(true,3000);socket.setTimeout(12000,()=>socket.destroy());socket.on('error',()=>{});socket.on('close',()=>{if(!closed){closed=true;onClose();}});socket.on('data',data=>{buffer+=decoder.write(data);if(buffer.length>MAX){socket.destroy();return;}let at;while((at=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,at);buffer=buffer.slice(at+1);try{onMessage(JSON.parse(line));}catch(_){socket.destroy();return;}}});return {send(message){if(socket.destroyed||socket.writableLength>MAX*2)return false;const data=JSON.stringify(message);if(data.length>MAX)return false;socket.write(data+'\n');return true;},close(){socket.destroy();}};}
function create({emit=()=>{}}={}){let server=null,link=null,role='off',code='',session='',joined=false,lastSequence=-1,pulse=null;const sockets=new Set();
function stop(){role='off';joined=false;if(pulse)clearInterval(pulse);pulse=null;for(const s of sockets)s.destroy();sockets.clear();link=null;if(server)server.close();server=null;}
async function host(options={}){stop();role='host';code=String(options.code||crypto.randomInt(100000,1000000));session=crypto.randomUUID();server=net.createServer(socket=>{if(joined||sockets.size>=4){socket.destroy();return;}sockets.add(socket);let authenticated=false,tokens=60,last=Date.now();const ch=channel(socket,m=>{if(!authenticated){if(m.type!=='hello'||m.code!==code||m.version!==VERSION){socket.destroy();return;}authenticated=true;joined=true;lastSequence=-1;link=ch;ch.send({type:'welcome',version:VERSION,session,teamId:'team-1'});emit({type:'joined',session});return;}if(m.type==='heartbeat')return;if(m.type!=='input'||m.session!==session||!Number.isInteger(m.seq)||m.seq<=lastSequence)return;const now=Date.now();tokens=Math.min(60,tokens+(now-last)*.06);last=now;if(tokens<1)return;tokens--;lastSequence=m.seq;emit({type:'input',teamId:'team-1',command:m});},()=>{sockets.delete(socket);if(authenticated&&role==='host'){joined=false;link=null;emit({type:'disconnected'});}});});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(options.port??PORT,options.bind||'0.0.0.0',resolve);});const port=server.address().port;pulse=setInterval(()=>link?.send({type:'heartbeat'}),2000);pulse.unref();const addresses=Object.values(os.networkInterfaces()).flat().filter(a=>a&&a.family==='IPv4'&&!a.internal).map(a=>a.address);return {role,code,port,addresses,version:VERSION};}
async function join(options){stop();role='guest';const host=String(options.host||'').trim();if(!host||host.length>253||!/^[-a-zA-Z0-9.:]+$/.test(host))throw Error('Dirección inválida');const socket=net.createConnection({host,port:options.port||PORT});sockets.add(socket);return new Promise((resolve,reject)=>{let welcomed=false;link=channel(socket,m=>{if(m.type==='welcome'&&m.version===VERSION){welcomed=true;joined=true;session=m.session;emit(m);resolve({role,teamId:m.teamId,session});}else if(welcomed&&m.type==='snapshot')emit(m);},()=>{if(!welcomed)reject(Error('No se pudo conectar: IP, código, versión o firewall'));if(role==='guest')emit({type:'disconnected'});});socket.once('connect',()=>link.send({type:'hello',version:VERSION,code:String(options.code||'')}));socket.once('error',reject);pulse=setInterval(()=>link?.send({type:'heartbeat'}),2000);pulse.unref();});}
return {host,join,stop,input(command){if(role==='guest'&&joined)link?.send({type:'input',...command,session});},publish(snapshot){if(role==='host'&&joined)link?.send({type:'snapshot',session,data:snapshot});},status(){return {role,joined,session};}};
}
module.exports={create,VERSION,PORT,channel};
