'use strict';const fs=require('fs'),path=require('path'),assert=require('assert');module.exports=async({win,errors,root})=>{const out=path.join(root,'qa-kaykit');fs.mkdirSync(out,{recursive:true});const ev=s=>win.webContents.executeJavaScript('(()=>{'+s+'})()',true),wait=ms=>new Promise(r=>setTimeout(r,ms)),cases=[],check=(n,v)=>{assert(v,n);cases.push(n);};try{
 await ev('CR3D.test.manual(false);CR3D.reset();CR3D.test.clearMortarArena();');await wait(300);let a=await ev('return CR3D.test.humanoidAudit();');check('KayKit retarget bank is active',a.kaykit.active&&a.kaykit.loaded>=19&&a.kaykit.catalog===130);
 await ev('CR3D.setInput("forward",true);');await wait(380);a=await ev('return CR3D.test.humanoidAudit();');check('Running uses KayKit clip',a.rigs[0].clip==='KK_Running_A');fs.writeFileSync(path.join(out,'01-run.png'),(await win.webContents.capturePage()).toPNG());
 await ev('CR3D.setInput("forward",false);CR3D.setInput("jump",true);');await wait(120);check('Air state uses jump clip',await ev('return CR3D.test.humanoidAudit().rigs[0].clip==="KK_Jump_Idle";'));fs.writeFileSync(path.join(out,'02-jump.png'),(await win.webContents.capturePage()).toPNG());await wait(850);
 await ev('CR3D.selectWeapon(0);');await wait(60);check('Changing weapon does not fake a shot',await ev('return !CR3D.test.humanoidAudit().rigs[0].clip.includes("Shooting");'));await wait(120);check('Pistol actually fires',await ev('return CR3D.fire();'));await wait(60);check('Pistol uses one-hand firing',await ev('return CR3D.test.humanoidAudit().rigs[0].clip==="KK_Ranged_1H_Shooting";'));await ev('CR3D.reload();');await wait(80);check('Reload uses matching one-hand animation',await ev('return CR3D.test.humanoidAudit().rigs[0].clip==="KK_Ranged_1H_Reload";'));await wait(1100);
 await ev('CR3D.selectWeapon(1);');await wait(180);check('Rifle actually fires',await ev('return CR3D.fire();'));await wait(40);check('Rifle uses two-hand firing',await ev('return CR3D.test.humanoidAudit().rigs[0].clip==="KK_Ranged_2H_Shooting";'));await wait(300);await ev('CR3D.test.hitPlayer(5);');await wait(40);check('Damage uses KayKit hit reaction',await ev('return CR3D.test.humanoidAudit().rigs[0].clip==="KK_Hit_A";'));
 await ev('dispatchEvent(new KeyboardEvent("keydown",{code:"F7"}));');await wait(100);const clock=await ev('return CR3D.snapshot().state.time;');await ev('dispatchEvent(new KeyboardEvent("keydown",{code:"KeyP"}));');await wait(80);check('Preview blocks unpause from gameplay keys',await ev('return CR3D.snapshot().state.paused&&CR3D.snapshot().state.time;')===clock);
 const catalog=await ev('return window.CRKayKitCatalog;'),samples=[];for(const name of catalog){await ev('return CR3D.test.previewAnimation('+JSON.stringify(name)+');');for(const fraction of [.05,.4,.8]){const g=await ev('return CR3D.test.probeAnimation('+fraction+');');assert(g.every(r=>!r.invalid&&r.bodyClearance>-.2),'Invalid pose '+name);samples.push({name,fraction,geometry:g});}}
 check('All 130 clips load locally and pose without invalid geometry',samples.length===390);fs.writeFileSync(path.join(out,'catalog-poses.json'),JSON.stringify(samples,null,2));fs.writeFileSync(path.join(out,'03-preview.png'),(await win.webContents.capturePage()).toPNG());
 await ev('CR3D.test.previewAnimation(null);dispatchEvent(new KeyboardEvent("keydown",{code:"F7"}));');await wait(100);check('Preview restores gameplay',await ev('return !CR3D.snapshot().state.paused;'));
 await ev('CR3D.test.previewAnimation("KK_Lockpick");CR3D.test.previewAnimation(null);');await wait(100);check('Closing preview cancels a pending clip',await ev('return !CR3D.test.animationPreviewActive();'));
 check('No renderer or frame faults',errors.length===0&&await ev('return CR3D.snapshot().render.frameFaults===0;'));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:true,cases,errors},null,2));console.log('KAYKIT QA PASS: '+cases.length+' checks · 390 sampled poses');await ev('CR3D.reset();');
 }catch(e){fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:false,error:e.stack,cases,errors},null,2));throw e;}};


