'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({win,errors,root})=>{
 const out=path.join(root,'qa-world');fs.mkdirSync(out,{recursive:true});
 const evaluate=code=>win.webContents.executeJavaScript(code,true),wait=ms=>new Promise(r=>setTimeout(r,ms));
 const cases=[],check=(name,value)=>{assert(value,name);cases.push(name);};
 const run=code=>evaluate('(()=>{'+code+'})()'),snapshot=()=>evaluate('CR3D.snapshot()');
 win.setContentSize(1360,840);await wait(250);
 await run('CR3D.reset();CR3D.test.manual(true);CR3D.test.step(.1);');
 const initial=await snapshot();
 check('Forest, reeds, fungi and water populate the world',initial.world.trees>400&&initial.world.reeds===9000&&initial.world.fungi===750&&initial.world.waterPockets===32);
 check('Fauna, rain and environmental collisions are bounded',initial.world.fauna===24&&initial.world.rainDrops===260&&initial.world.colliders>400);
 const faces=await evaluate('CR3D.test.faces()');check('Every creature including the boss has a curved textured expression',faces.length===35&&faces.every(f=>f.curved&&f.textured&&f.finite)&&faces.some(f=>f.boss));
 check('All three enemy roles have authored facial variants',new Set(faces.map(f=>f.role)).size===3);
 await wait(120);fs.writeFileSync(path.join(out,'01-marisma.png'),(await win.webContents.capturePage()).toPNG());
 for(const [id,x,z,yaw] of [['forge',1450,-900,-.4],['rift',650,-2250,0],['heart',-1750,-1400,0]]){
   await run(`CR3D.teleport(${x},${z});CR3D.setCamera(${yaw},.18);CR3D.test.step(.05);`);
   check('Distinct region '+id,(await snapshot()).world.region===id);
   await wait(180);fs.writeFileSync(path.join(out,'region-'+id+'.png'),(await win.webContents.capturePage()).toPNG());
 }
 check('Exploration awards discovery progress',(await snapshot()).expedition.visited.length===4);
 await run('CR3D.reset();CR3D.fire();');
 check('Pistol consumes one cartridge',(await snapshot()).weapon.ammo===13);
 await run('CR3D.reload();CR3D.setPaused(true);');const frozen=(await snapshot()).weapon.reload;
 await run('CR3D.test.step(2);');check('Reload is frozen by pause',(await snapshot()).weapon.reload===frozen);
 await run('CR3D.setPaused(false);CR3D.test.step(1.2);');check('Reload restores magazine',(await snapshot()).weapon.ammo===14);
 await run('CR3D.selectWeapon(1);CR3D.test.step(.15);CR3D.setInput("fire",true);CR3D.test.step(.4);CR3D.setInput("fire",false);');
 check('Automatic rifle has its own rate and magazine',(await snapshot()).weapon.ammo<=24&&(await snapshot()).weapon.name==='Rifle');
 await run('CR3D.selectWeapon(2);CR3D.test.step(.4);');const before=(await snapshot()).projectiles;
 await run('CR3D.fire();');check('Shotgun launches eight pellets',(await snapshot()).projectiles===before+8&&(await snapshot()).weapon.ammo===5);
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'M'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'M'});await wait(80);
 check('M key opens the map',await evaluate('!document.getElementById("map-panel").hidden'));
 fs.writeFileSync(path.join(out,'02-mapa.png'),(await win.webContents.capturePage()).toPNG());
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'M'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'M'});
 await run('CR3D.reset();const s=CR3D.test.sites()[0];CR3D.teleport(s.x,s.z);');
 check('Threatened relay cannot be activated',!(await evaluate('CR3D.interact()')));
 await run('const s=CR3D.test.sites()[0];CR3D.test.clearAround(s.x,s.z);CR3D.interact();CR3D.continueRun();');
 check('Checkpoint restores relay progress',(await snapshot()).expedition.relays[0]);
 for(let i=1;i<3;i++)await run(`const s=CR3D.test.sites()[${i}];CR3D.test.clearAround(s.x,s.z);CR3D.teleport(s.x,s.z);CR3D.interact();`);
 check('Three relays awaken the boss',(await snapshot()).expedition.phase==='boss'&&(await evaluate('CR3D.test.boss().alive')));
 await run('const b=CR3D.test.boss();CR3D.teleport(b.position[0],b.position[2]+310);CR3D.test.clearAround(b.position[0],b.position[2]);CR3D.test.step(2.5);');
 check('Boss telegraphs an attack',await evaluate('!document.getElementById("boss-info").hidden'));
 await wait(180);fs.writeFileSync(path.join(out,'03-jefe.png'),(await win.webContents.capturePage()).toPNG());
 await run('CR3D.test.damageBoss(470);CR3D.test.step(.5);');
 check('Boss enters phase two and releases projectiles',(await evaluate('CR3D.test.boss().hp'))===430&&(await snapshot()).projectiles>0);
 await run('CR3D.test.damageBoss(1000);');check('Boss defeat enables extraction',(await snapshot()).expedition.phase==='extract');
 await run('const b=CR3D.test.boss();CR3D.teleport(b.position[0],b.position[2]);CR3D.test.step(.3);');
 check('Boss loot grants fragments',(await snapshot()).expedition.shards>=50);
 await run('const s=CR3D.test.sites()[4];CR3D.teleport(s.x,s.z);CR3D.test.clearAround(s.x,s.z);CR3D.interact();');
 check('Camp spends fragments to calibrate arsenal',(await snapshot()).expedition.upgrades===1&&(await snapshot()).expedition.shards===30);
 await run('CR3D.continueRun();');check('Checkpoint retains extraction and calibration',(await snapshot()).expedition.phase==='extract'&&(await snapshot()).expedition.upgrades===1&&!(await evaluate('CR3D.test.boss().alive')));
 await run('const s=CR3D.test.sites()[4];CR3D.teleport(s.x,s.z);CR3D.test.clearAround(s.x,s.z);CR3D.test.step(5.1);');
 check('Extraction completes the expedition',(await snapshot()).state.won&&(await snapshot()).expedition.phase==='complete');
 await run('CR3D.continueRun();');check('Completed checkpoint does not respawn the defeated encounter',(await snapshot()).expedition.phase==='relays'&&!(await snapshot()).state.won);
 await run('CR3D.reset();CR3D.audio.settings(.65,false);');await evaluate('CR3D.audio.start()');await run('CR3D.test.step(.1);CR3D.audio.event("shot",null,2);');await wait(250);
 const activeAudio=(await snapshot()).audio;
 check('Audio context runs and emits actual non-clipping samples',activeAudio.running&&activeAudio.rms>0&&activeAudio.peak<1);
 await run('for(let i=0;i<100;i++)CR3D.audio.event("boss");');check('Transient audio stays within voice budget',(await snapshot()).audio.voices<=32);
 await run('CR3D.audio.settings(.65,true);');await wait(900);check('Mute silences the full mix',(await snapshot()).audio.rms<.0001);
 await run('CR3D.audio.settings(.65,false);CR3D.setPaused(true);');await wait(900);check('Pause silences the full mix',(await snapshot()).audio.rms<.0001);
 await wait(1600);check('Transient audio nodes are released',(await snapshot()).audio.voices===0);
 await run('CR3D.reset();CR3D.test.manual(false);');
 const frames=await evaluate('new Promise(resolve=>{let n=0,start=performance.now();function tick(){if(++n>=60)resolve({frames:n,seconds:(performance.now()-start)/1000});else requestAnimationFrame(tick);}requestAnimationFrame(tick);})');
 check('Live simulation advances without manual stepping',(await snapshot()).state.time>initial.state.time);
 check('No renderer errors',errors.length===0);
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:true,cases,initial,activeAudio,frames,final:await snapshot(),errors},null,2));
 console.log('WORLD QA PASS: '+cases.length+' checks; errors='+errors.length+'; sampled FPS='+Math.round(frames.frames/frames.seconds));
};
