'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({win,errors,root})=>{
 const out=path.join(root,'qa-umbral');fs.mkdirSync(out,{recursive:true});const cases=[],check=(name,value)=>{assert(value,name);cases.push(name);},ev=s=>win.webContents.executeJavaScript('(()=>{'+s+'})()',true),get=s=>ev('return '+s+';'),wait=ms=>new Promise(r=>setTimeout(r,ms));
 await get('CR3D.audio.start()');await ev('CR3D.reset();CR3D.test.manual(true);CR3D.test.clearMortarArena();const p=CR3D.test.dimension().portal;CR3D.teleport(p.x,p.z+65);');
 check('Portal is a small black hole in both dimensions',(await get('CR3D.test.dimension().portal.kind'))==='black-hole'&&(await get('CR3D.test.dimension().portal.visualRadius'))===21);
 const inventory=await get('JSON.stringify(CR3D.snapshot().loadout)');
 check('E starts a visible timed transit',await get('CR3D.interact()'));
 await ev('CR3D.test.step(1.15);');check('Space transition does not switch maps prematurely',(await get('CR3D.test.dimension().id'))===0&&(await get('CR3D.test.dimension().transit.active')));
 check('Repeated E and firing cannot escape or duplicate transit',!(await get('CR3D.interact()'))&&!(await get('CR3D.fire()')));
 await wait(130);fs.writeFileSync(path.join(out,'01-spaghettification.png'),(await win.webContents.capturePage()).toPNG());
 const time=await get('CR3D.test.dimension().transit.elapsed');await ev('CR3D.setPaused(true);CR3D.test.step(.5);');check('Pause freezes the dimensional animation',(await get('CR3D.test.dimension().transit.elapsed'))===time);
 await ev('CR3D.setPaused(false);CR3D.test.step(2);');const map=await get('CR3D.test.dimension()');check('Travel completes once and restores control',map.id===1&&!map.transit.active&&map.visible===1);
 check('Transit consumes no arsenal resources',(await get('JSON.stringify(CR3D.snapshot().loadout)'))===inventory);
 check('Dimension has tactical cover and three connected route recipes',map.content.covers===16&&map.content.routes===3&&map.content.points.length===4);
 check('Existing Growth identity remains intact',map.aesthetic.style==='growth-marsh'&&map.aesthetic.orbs===6);
 check('Dimensional soundscape changes with the map',(await get('CR3D.snapshot().audio.growth.soundscape'))==='resonant-growth');
 await ev('CR3D.test.clearMortarArena();for(let i=0;i<3;i++){const s=CR3D.test.sites()[i];CR3D.teleport(s.x,s.z);CR3D.interact();}');
 check('All three Umbral II relays activate the actual boss',(await get('CR3D.snapshot().expedition.relays.every(Boolean)'))&&(await get('CR3D.test.boss().alive')));
 await ev('CR3D.teleport(-430,-570);CR3D.setCamera(.55,.18);');await wait(130);fs.writeFileSync(path.join(out,'04-receptor-cover.png'),(await win.webContents.capturePage()).toPNG());
 await ev('CR3D.test.damageBoss(10000);const s=CR3D.test.sites()[4];CR3D.teleport(s.x,s.z);CR3D.test.step(5.1);');check('Boss and extraction complete Umbral II expedition',(await get('CR3D.snapshot().state.won')));
 await ev('localStorage.setItem("CR3D-expedition-v1","origin-checkpoint");localStorage.setItem("CR3D-inventory-v1","origin-inventory");document.getElementById("match-dimension").value="1";document.getElementById("explore-dimension").click();');
 check('Exploration button starts the selected actual map',(await get('CR3D.test.dimension().id'))===1&&!(await get('CR3D.snapshot().state.won')));
 check('Starting an alternate expedition preserves origin disk checkpoint and inventory',(await get('localStorage.getItem("CR3D-expedition-v1")'))==='origin-checkpoint'&&(await get('localStorage.getItem("CR3D-inventory-v1")'))==='origin-inventory');
 await ev('CR3D.reset();CR3D.match.start({tactical:false,dimension:1,teams:[{name:"Receptores",members:["Luz"]},{name:"Archivo",members:["Eco"]}]});CR3D.test.clearMortarArena();');
 check('A full local match can start directly in Umbral II',(await get('CR3D.test.dimension().id'))===1&&(await get('CR3D.match.snapshot().members[0].name'))==='Luz');
 await ev('const s=CR3D.test.sites()[0];CR3D.teleport(s.x,s.z);CR3D.interact();CR3D.test.step(2.1);');check('Local relay scoring works on the alternate terrain',(await get('CR3D.match.snapshot().teams[0].score'))===5);
 await ev('CR3D.match.end();CR3D.test.step(5.1);');check('Air supplies still precede the next turn',(await get('CR3D.match.snapshot().phase'))==='supply'&&(await get('CR3D.snapshot().supplies.crates.length'))===1);
 await ev('CR3D.test.step(3);');check('Next player and camera remain on the same dimension',(await get('CR3D.match.snapshot().activeId'))==='actor-1-0'&&(await get('CR3D.test.dimension().id'))===1&&(await get('CR3D.diagnostics().scene.ok')));
 await ev('CR3D.teleport(0,-260);CR3D.setCamera(0,.18);CR3D.test.step(.1);');await wait(160);fs.writeFileSync(path.join(out,'02-señal-sumergida.png'),(await win.webContents.capturePage()).toPNG());
 await ev('CR3D.setPaused(true);');await wait(100);fs.writeFileSync(path.join(out,'03-map-selection.png'),(await win.webContents.capturePage()).toPNG());check('Menu exposes both maps and a direct exploration action',(await get('document.getElementById("match-dimension").options.length'))===2&&!!(await get('document.getElementById("explore-dimension")')));
 await ev('CR3D.reset();CR3D.test.clearMortarArena();const p=CR3D.test.dimension().portal;CR3D.teleport(p.x,p.z+65);CR3D.interact();CR3D.test.step(.6);CR3D.reset();');check('Restart safely cancels transit and preserves Umbral I identity',!(await get('CR3D.test.dimension().transit.active'))&&(await get('CR3D.test.dimension().aesthetic.style'))==='original-marsh');
 check('No renderer errors or frame faults',errors.length===0&&(await get('CR3D.snapshot().render.frameFaults'))===0);
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:true,cases,map,errors},null,2));await ev('CR3D.test.manual(false);');console.log('UMBRAL QA PASS: '+cases.length+' checks');
};
