'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({win,errors,root})=>{
 const out=path.join(root,'qa-mortar');fs.mkdirSync(out,{recursive:true});
 const evaluate=code=>win.webContents.executeJavaScript(code,true),wait=ms=>new Promise(r=>setTimeout(r,ms)),cases=[];
 const check=(n,v)=>{assert(v,n);cases.push(n);},run=code=>evaluate('(()=>{'+code+'})()'),snapshot=()=>evaluate('CR3D.mortar.snapshot()');
 await run('CR3D.reset();CR3D.test.manual(true);CR3D.selectWeapon(3);');
 check('Mortar slot stays locked before pickup',(await evaluate('CR3D.snapshot().weapon.name'))==='Pistola'&&!(await snapshot()).owned);
 check('Pickup requires actual proximity',!(await evaluate('CR3D.mortar.collect()')));
 await run('const p=CR3D.mortar.snapshot().pickup;CR3D.teleport(p.x,p.z);CR3D.test.step(.1);');
 check('Near weapon displays the pickup prompt',await evaluate('!document.getElementById("pickup-prompt").hidden'));
 await wait(150);fs.writeFileSync(path.join(out,'01-pickup.png'),(await win.webContents.capturePage()).toPNG());
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'E'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'E'});await wait(100);
 check('E collects and equips the mortar',(await snapshot()).owned&&(await evaluate('CR3D.snapshot().weapon.name'))==='Mortero');
 check('Mortar icon loads locally',await evaluate('document.querySelector(".weapon-slots img").naturalWidth>0'));
 check('Weapon slots and camera controls do not overlap',await run('const a=document.querySelector(".arsenal").getBoundingClientRect(),b=document.getElementById("camera-toggle").getBoundingClientRect();return b.bottom<a.top||a.bottom<b.top;'));
 check('A collected pickup cannot be duplicated',!(await evaluate('CR3D.mortar.collect()')));
 await run('CR3D.continueRun();CR3D.selectWeapon(3);CR3D.test.clearMortarArena();CR3D.setCamera(0,.32);CR3D.test.mortarAim(0,-170);CR3D.test.step(.15);');
 check('Checkpoint preserves collected inventory',(await snapshot()).owned);
 const preview=await snapshot();check('Preview has an impact point and positive flight time',preview.prediction?.flight>0&&preview.prediction.range>20);
 check('Telemetry draws one hundred dense ballistic samples',preview.telemetry.points===100&&preview.telemetry.maxSegment<8);
 const telemetryBefore=preview.telemetry.frames;await run('for(let i=0;i<12;i++){CR3D.setCamera(i*.002,.32);CR3D.test.step(1/60);}');const movingTelemetry=await snapshot();
 check('Telemetry refreshes at render cadence without a fixed low-rate gate',movingTelemetry.telemetry.standard==='render-cadence-exponential'&&movingTelemetry.telemetry.frames>=telemetryBefore+12&&movingTelemetry.telemetry.response===32);
 check('Equipped mortar displays flight telemetry',await evaluate('!document.getElementById("mortar-readout").hidden'));
 await wait(150);fs.writeFileSync(path.join(out,'02-trajectory.png'),(await win.webContents.capturePage()).toPNG());
 const predictedAtFire=await snapshot();
 await run('CR3D.fire();');
 check('Firing spends one shell',(await evaluate('CR3D.snapshot().weapon.ammo'))===2&&(await snapshot()).shells===1);
 await run('CR3D.test.step(.12);CR3D.setPaused(true);');const frozen=await evaluate('CR3D.mortar.test.shells()');
 await run('CR3D.test.step(1);');check('Pause freezes ballistic shells',JSON.stringify(await evaluate('CR3D.mortar.test.shells()'))===JSON.stringify(frozen));
 await run('CR3D.setPaused(false);');
 await run('CR3D.test.step('+Math.max(.02,predictedAtFire.prediction.flight-.12+.04)+');');
 const impact=await snapshot();
 check('Predicted and actual swept impact agree',impact.lastImpact&&Math.hypot(...impact.lastImpact.map((v,i)=>v-predictedAtFire.prediction.impact[i]))<.2);
 check('Impact creates a compact bounded explosion',impact.effects===1&&impact.radius===42&&impact.shells===0);
 await run('CR3D.test.step(.08);');await wait(120);fs.writeFileSync(path.join(out,'03-fire.png'),(await win.webContents.capturePage()).toPNG());
 await run('CR3D.test.step(.6);');await wait(120);fs.writeFileSync(path.join(out,'04-smoke.png'),(await win.webContents.capturePage()).toPNG());
 await run('CR3D.reload();CR3D.test.step(2.4);');check('Mortar reload restores its three-shell magazine',(await evaluate('CR3D.snapshot().weapon.ammo'))===3);
 await run('CR3D.selectWeapon(0);CR3D.test.step(.1);');check('Switching weapons hides the arc',await evaluate('document.getElementById("mortar-readout").hidden'));
 await run('CR3D.test.step(3.3);');check('Fire, smoke and transient light finish cleanly',(await snapshot()).effects===0);
 await run('CR3D.reset();CR3D.test.arrangeEnemy(0,0,-85);CR3D.test.arrangeEnemy(2,140,-85);');
 const farHp=await evaluate('CR3D.test.enemy(2).hp');
 await run('const e=CR3D.test.enemy(0);CR3D.mortar.test.detonate(e.position,95);');
 check('Explosion damages a nearby creature',!(await evaluate('CR3D.test.enemy(0).alive')));
 check('Creatures outside blast radius remain intact',(await evaluate('CR3D.test.enemy(2).hp'))===farHp);
 await run('CR3D.reset();CR3D.test.clearMortarArena();');
 check('Ballistic swept collisions stop at real cover',await run('const b=CR3D.test.cover(),y=(b.min.y+b.max.y)/2,z=(b.min.z+b.max.z)/2;return CR3D.mortar.test.sweep([b.min.x-20,y,z],[b.max.x+20,y,z]);'));
 await run('CR3D.reset();const b=CR3D.test.treeCover(),z=(b.min.z+b.max.z)/2;CR3D.test.arrangeEnemy(2,b.max.x+10,z);');const protectedHp=await evaluate('CR3D.test.enemy(2).hp');
 await run('const b=CR3D.test.treeCover(),z=(b.min.z+b.max.z)/2;CR3D.mortar.test.detonate([b.min.x-10,b.min.y+23,z],95);');
 check('Cover shields creatures from the compact blast',(await evaluate('CR3D.test.enemy(2).hp'))===protectedHp);
 await run('for(let i=0;i<10;i++)CR3D.mortar.test.detonate([0,40,-100],0);');check('Repeated explosions respect effect pool',(await snapshot()).effects<=4);
 await run('CR3D.reset();');check('New expedition respawns pickup and clears effects',!(await snapshot()).owned&&(await snapshot()).shells===0&&(await snapshot()).effects===0);
 check('Mortar integration has no renderer errors',errors.length===0);
 await run('CR3D.test.manual(false);');
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:true,cases,preview,predictedAtFire,impact,errors},null,2));console.log('MORTAR QA PASS: '+cases.length+' checks; errors='+errors.length);
};
