'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({win,errors,root})=>{
 const out=path.join(root,'qa-combat');fs.mkdirSync(out,{recursive:true});
 const evaluate=code=>win.webContents.executeJavaScript(code,true),wait=ms=>new Promise(r=>setTimeout(r,ms));
 const cases=[];const check=(name,value)=>{assert(value,name);cases.push(name);};
 for(let i=0;i<100;i++){if(await evaluate('!!window.CR3D'))break;await wait(100);}
 await evaluate('CR3D.test.manual(true);CR3D.reset()');
 const run=code=>evaluate('(()=>{'+code+'})()');
 const state=()=>evaluate('CR3D.snapshot()');
 check('Scene initialized',(await state()).ready);
 await run('CR3D.setInput("forward",true);CR3D.test.step(.2);');const straight=(await state()).speed;
 await run('CR3D.reset();CR3D.setInput("forward",true);CR3D.setInput("right",true);CR3D.test.step(.2);');
 check('Diagonal movement does not gain speed',Math.abs((await state()).speed-straight)<.01);
 await run('CR3D.reset();');check('Fast shots cannot cross cover',await evaluate('CR3D.test.blockedShot()'));
 await run('CR3D.setInput("forward",true);CR3D.test.step(.5);CR3D.setInput("forward",false);');
 check('Acceleration moves player',(await state()).travelled>60);
 await run('CR3D.reset();CR3D.setInput("jump",true);CR3D.setInput("forward",true);CR3D.setInput("dash",true);CR3D.test.step(.13);');
 const combo=await state();check('Jump + directional dash combine',combo.height>20&&combo.speed>400&&combo.state.cooldown>0);
 await run('CR3D.setInput("forward",false);CR3D.test.step(1.1);');
 check('Gravity returns to terrain',Math.abs((await state()).height)<.1);
 await run('CR3D.reset();CR3D.test.step(.05);CR3D.setInput("dash",true);CR3D.test.step(.05);CR3D.setInput("dash",true);CR3D.test.step(.3);');
 check('Dash cannot repeat during cooldown',(await state()).state.dash===0&&(await state()).state.cooldown>0);
 await run('CR3D.reset();CR3D.test.arrangeEnemy(0,0,-115);CR3D.test.step(.4);');
 const hp=await evaluate('CR3D.test.enemy(0).hp');
 await run('CR3D.test.shootAt(0);CR3D.test.step(.15);');
 check('Swept projectile damages enemy',await evaluate('CR3D.test.enemy(0).hp')<hp);
 await run('CR3D.test.shootAt(0);CR3D.test.step(.15);CR3D.test.shootAt(0);CR3D.test.step(.15);');
 check('Enemy dies and kill count advances',!(await evaluate('CR3D.test.enemy(0).alive'))&&(await state()).state.kills===1);
 await run('CR3D.reset();CR3D.test.arrangeEnemy(0,0,-60);CR3D.test.step(2);');
 check('Enemy telegraph leads to damage',(await state()).state.hp<100);
 check('Enemy/player remain separated',await evaluate('CR3D.test.separated()'));
 await run('CR3D.reset();CR3D.test.arrangeEnemy(1,0,-250);CR3D.test.step(.5);');
 check('Ranged enemy fires',(await state()).projectiles>0);
 await run('CR3D.test.step(1.2);');
 check('Hostile projectile can damage player',(await state()).state.hp<100);
 await run('CR3D.reset();CR3D.setMode("fixed");CR3D.test.arrangeEnemy(2,0,-190);CR3D.setCamera(0,.18);CR3D.test.aimAt(2);CR3D.fire();CR3D.test.step(.35);');
 check('Cursor aim hits actual target',await evaluate('CR3D.test.enemy(2).hp<150'));
 await run('CR3D.setPaused(true);');const paused=await state();await run('CR3D.test.step(1);');
 check('Pause freezes simulation',(await state()).state.time===paused.state.time);
 await run('CR3D.reset();CR3D.test.step(1.1);CR3D.test.hitPlayer(200);');
 check('Death stops combat',(await state()).state.dead&&(await state()).state.hp===0);
 await run('CR3D.reset();');check('Restart restores life and enemies',(await state()).state.hp===100&&(await state()).targets===34);
 for(const mode of ['free','fixed','auto']){await evaluate('CR3D.setMode('+JSON.stringify(mode)+')');check('Camera mode '+mode,(await state()).state.cameraMode===mode);}
 await run('CR3D.setMode("free");CR3D.test.arrangeEnemy(0,-60,-180);CR3D.test.arrangeEnemy(1,70,-290);CR3D.test.arrangeEnemy(2,100,-220);CR3D.setCamera(0,.12);CR3D.test.step(.1);');
 await wait(200);fs.writeFileSync(path.join(out,'01-combat.png'),(await win.webContents.capturePage()).toPNG());
 await run('CR3D.setInput("jump",true);CR3D.setInput("right",true);CR3D.setInput("dash",true);CR3D.test.step(.13);');
 await wait(150);fs.writeFileSync(path.join(out,'02-jump-dash.png'),(await win.webContents.capturePage()).toPNG());
 await run('CR3D.reset();const b=CR3D.test.cover();CR3D.teleport((b.min.x+b.max.x)/2,b.max.z+65);CR3D.setCamera(Math.PI,.16);');
 check('Camera avoids cover',await evaluate('CR3D.test.cameraClear()'));
 await run('CR3D.setCamera(0,.18);CR3D.setInput("forward",true);CR3D.setInput("dash",true);CR3D.test.step(.5);CR3D.setInput("forward",false);');
 check('Dash respects solid obstacles',await evaluate('CR3D.test.bodyClear()'));
 // Real keyboard events exercise the same bindings the user plays with.
 await run('CR3D.reset();');win.webContents.sendInputEvent({type:'keyDown',keyCode:'Space'});await wait(80);await run('CR3D.test.step(.15);');
 check('Space key triggers jump',(await state()).height>15);
 win.webContents.sendInputEvent({type:'keyUp',keyCode:'Space'});
 await run('CR3D.setInput("forward",true);window.dispatchEvent(new Event("blur"));');
 check('Losing focus pauses and clears controls',(await state()).state.paused);
 await run('CR3D.reset();CR3D.teleport(2700,-1900);CR3D.setInput("forward",true);CR3D.test.step(.6);CR3D.setInput("forward",false);');
 check('Large terrain remains traversable',Math.abs((await state()).position[0])>2500);
 await run('CR3D.reset();CR3D.test.step(1.1);CR3D.test.manual(false);');const beforeHit=await state();await run('CR3D.test.hitPlayer(14);');await wait(350);const afterHit=await state();
 check('A live impact cannot stop the animation frame chain',afterHit.render.frameSerial>beforeHit.render.frameSerial&&afterHit.state.hp===86&&!afterHit.render.lastFrameError);
 check('Zero-length impact direction keeps position and speed finite',[...afterHit.position,afterHit.speed].every(Number.isFinite));
 await run('CR3D.test.manual(true);');
 win.setContentSize(960,620);await wait(250);fs.writeFileSync(path.join(out,'03-resize.png'),(await win.webContents.capturePage()).toPNG());
 check('No console errors',errors.length===0);
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:true,cases,combo,final:await state(),errors},null,2));
 console.log('COMBAT QA PASS: '+cases.length+' checks; errors='+errors.length);
};
