'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({win,errors,root})=>{
 const out=path.join(root,'qa-terror');fs.mkdirSync(out,{recursive:true});
 const evaluate=code=>win.webContents.executeJavaScript(code,true),wait=ms=>new Promise(r=>setTimeout(r,ms));
 const cases=[],check=(name,value)=>{assert(value,name);cases.push(name);};
 const run=code=>evaluate('(()=>{'+code+'})()'),snapshot=()=>evaluate('CR3D.snapshot()');
 await run('CR3D.reset();CR3D.test.manual(true);');let initial=await snapshot();
 check('Candle starts lit with a finite four-minute resource',initial.survival.lit&&initial.survival.fuel===240&&initial.survival.matches===3);
 check('Post process exposes vignette, grain and chromatic pass',initial.post.enabled&&initial.post.vignette&&initial.post.grain&&initial.post.chromatic);
 await run('CR3D.test.step(2);');let burned=await snapshot();
 check('Simulation time consumes candle fuel',burned.survival.fuel<initial.survival.fuel-1.9);
 await run('CR3D.test.survival({fuel:0,emergency:0,lit:false,fear:.7});CR3D.test.step(.5);');let dark=await snapshot();
 check('Darkness raises fear and applies bounded movement pressure',dark.survival.darkness>.75&&dark.survival.fear>.7&&dark.survival.movementMultiplier>=.88);
 check('Fear exposes a bounded enemy aggression multiplier',dark.survival.aggressionMultiplier>1&&dark.survival.aggressionMultiplier<=1.22);
 const relit=await run('return CR3D.test.useMatch();');let matched=await snapshot();
 check('Emergency match relights an empty candle and consumes one match',relit&&matched.survival.lit&&matched.survival.emergency>20&&matched.survival.matches===2);
 await evaluate('CR3D.test.startTerrorAudio()');await wait(350);let audio=await snapshot();
 check('Terror audio shares the running production AudioContext',audio.terrorAudio.started&&audio.terrorAudio.sharedContext&&audio.audio.running);
 await evaluate('CR3D.terrorAudio.reset()');
 await evaluate('(()=>{const p=CR3D.snapshot().position;for(let i=0;i<20;i++)CR3D.terrorAudio.whisper({x:p[0]+80+i,y:p[1],z:p[2]-120},{duration:.6});})()');audio=await snapshot();
 check('Spatial fear voices remain inside their fixed budget',audio.terrorAudio.voices<=audio.terrorAudio.voiceLimit);
 await evaluate('Promise.all(Array.from({length:8},()=>CR3D.test.startTerrorAudio()))');
 check('Concurrent audio startup never duplicates the permanent graph',(await snapshot()).terrorAudio.permanentNodes===audio.terrorAudio.permanentNodes);
 await wait(800);check('Completed fear voices retire without permanent node growth',(await snapshot()).terrorAudio.voices===0&&(await snapshot()).terrorAudio.permanentNodes===audio.terrorAudio.permanentNodes);
 await run('CR3D.test.survival({fuel:0,emergency:0,lit:false,fear:.94});CR3D.test.step(.3);');await wait(180);const panic=await snapshot();
 check('Panic reaches the WebGL post-process uniforms',panic.post.fear>.9&&panic.post.darkness>.75);
 fs.writeFileSync(path.join(out,'01-candle-panic.png'),(await win.webContents.capturePage()).toPNG());
 await run('CR3D.reset();');const reset=await snapshot();
 check('Restart restores candle, matches and fear',reset.survival.lit&&reset.survival.matches===3&&reset.survival.fear===0);
 check('No console errors in survival stack',errors.length===0);
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:true,cases,initial,burned,dark,matched,audio,panic,reset,errors},null,2));
 console.log('TERROR QA PASS: '+cases.length+' checks; errors='+errors.length);
};
